[2022-04-07 19:26:37,661] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2018-07-01T00:00:00+00:00 [queued]>
[2022-04-07 19:26:37,723] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2018-07-01T00:00:00+00:00 [queued]>
[2022-04-07 19:26:37,723] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:26:37,728] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:26:37,728] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:26:38,574] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_users.create_users_stack_overflow_data_external_table> on 2018-07-01 00:00:00+00:00
[2022-04-07 19:26:38,632] {standard_task_runner.py:52} INFO - Started process 4708 to run task
[2022-04-07 19:26:38,713] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_users.create_users_stack_overflow_data_external_table', 'scheduled__2018-07-01T00:00:00+00:00', '--job-id', '13012', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmppdyyi_dv', '--error-file', '/tmp/tmpc55p1gjw']
[2022-04-07 19:26:38,748] {standard_task_runner.py:80} INFO - Job 13012: Subtask create_external_users.create_users_stack_overflow_data_external_table
[2022-04-07 19:26:39,043] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2018-07-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:26:39,266] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:26:39,352] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_users.create_users_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2018-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-07-01T00:00:00+00:00
[2022-04-07 19:26:39,357] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:26:40,194] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_users.create_users_stack_overflow_data_external_table, execution_date=20180701T000000, start_date=20220407T192637, end_date=20220407T192640
[2022-04-07 19:26:40,374] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 19:26:40,539] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:19:19,461] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2018-07-01T00:00:00+00:00 [queued]>
[2022-04-07 22:19:19,498] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2018-07-01T00:00:00+00:00 [queued]>
[2022-04-07 22:19:19,498] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:19:19,498] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:19:19,498] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:19:19,850] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_users.create_users_stack_overflow_data_external_table> on 2018-07-01 00:00:00+00:00
[2022-04-07 22:19:19,877] {standard_task_runner.py:52} INFO - Started process 6911 to run task
[2022-04-07 22:19:19,958] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_users.create_users_stack_overflow_data_external_table', 'scheduled__2018-07-01T00:00:00+00:00', '--job-id', '14264', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmp2tbhfydu', '--error-file', '/tmp/tmper_96627']
[2022-04-07 22:19:19,959] {standard_task_runner.py:80} INFO - Job 14264: Subtask create_external_users.create_users_stack_overflow_data_external_table
[2022-04-07 22:19:20,336] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2018-07-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:19:20,591] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:19:20,682] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_users.create_users_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2018-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-07-01T00:00:00+00:00
[2022-04-07 22:19:20,684] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:19:21,733] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_users.create_users_stack_overflow_data_external_table, execution_date=20180701T000000, start_date=20220407T221919, end_date=20220407T221921
[2022-04-07 22:19:21,836] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:19:21,950] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
