[2022-04-07 19:25:37,141] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2017-12-01T00:00:00+00:00 [queued]>
[2022-04-07 19:25:37,267] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2017-12-01T00:00:00+00:00 [queued]>
[2022-04-07 19:25:37,268] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:25:37,268] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:25:37,268] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:25:37,900] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_users.create_users_stack_overflow_data_external_table> on 2017-12-01 00:00:00+00:00
[2022-04-07 19:25:37,927] {standard_task_runner.py:52} INFO - Started process 4267 to run task
[2022-04-07 19:25:37,971] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_users.create_users_stack_overflow_data_external_table', 'scheduled__2017-12-01T00:00:00+00:00', '--job-id', '12947', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpfjkx756x', '--error-file', '/tmp/tmpkoqdc2y6']
[2022-04-07 19:25:37,988] {standard_task_runner.py:80} INFO - Job 12947: Subtask create_external_users.create_users_stack_overflow_data_external_table
[2022-04-07 19:25:38,482] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2017-12-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:25:38,979] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:25:39,098] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_users.create_users_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2017-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-12-01T00:00:00+00:00
[2022-04-07 19:25:39,102] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:25:41,732] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_users.create_users_stack_overflow_data_external_table, execution_date=20171201T000000, start_date=20220407T192537, end_date=20220407T192541
[2022-04-07 19:25:41,920] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 19:25:42,201] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:18:42,264] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2017-12-01T00:00:00+00:00 [queued]>
[2022-04-07 22:18:42,313] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2017-12-01T00:00:00+00:00 [queued]>
[2022-04-07 22:18:42,313] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:18:42,313] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:18:42,313] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:18:43,095] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_users.create_users_stack_overflow_data_external_table> on 2017-12-01 00:00:00+00:00
[2022-04-07 22:18:43,145] {standard_task_runner.py:52} INFO - Started process 6592 to run task
[2022-04-07 22:18:43,193] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_users.create_users_stack_overflow_data_external_table', 'scheduled__2017-12-01T00:00:00+00:00', '--job-id', '14207', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmptdr5cjpl', '--error-file', '/tmp/tmpngts80j1']
[2022-04-07 22:18:43,194] {standard_task_runner.py:80} INFO - Job 14207: Subtask create_external_users.create_users_stack_overflow_data_external_table
[2022-04-07 22:18:43,532] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2017-12-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:18:43,666] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:18:43,716] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_users.create_users_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2017-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-12-01T00:00:00+00:00
[2022-04-07 22:18:43,719] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:18:44,890] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_users.create_users_stack_overflow_data_external_table, execution_date=20171201T000000, start_date=20220407T221842, end_date=20220407T221844
[2022-04-07 22:18:45,004] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:18:45,204] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
