[2022-04-07 19:18:01,142] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table scheduled__2011-03-01T00:00:00+00:00 [queued]>
[2022-04-07 19:18:01,198] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table scheduled__2011-03-01T00:00:00+00:00 [queued]>
[2022-04-07 19:18:01,198] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:18:01,198] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:18:01,199] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:18:01,857] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table> on 2011-03-01 00:00:00+00:00
[2022-04-07 19:18:01,875] {standard_task_runner.py:52} INFO - Started process 917 to run task
[2022-04-07 19:18:01,919] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table', 'scheduled__2011-03-01T00:00:00+00:00', '--job-id', '12459', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpmt_cbw6q', '--error-file', '/tmp/tmp8ak6p9h4']
[2022-04-07 19:18:01,937] {standard_task_runner.py:80} INFO - Job 12459: Subtask create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table
[2022-04-07 19:18:02,207] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table scheduled__2011-03-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:18:02,404] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2011-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2011-03-01T00:00:00+00:00
[2022-04-07 19:18:02,406] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:18:03,759] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1135, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 414, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/de-stack-overflow/datasets/stack_overflow_data/tables?prettyPrint=false: Error while reading table: posts_questions_stack_overflow_data_external_table, error message: Failed to expand table posts_questions_stack_overflow_data_external_table with file pattern gs://dtc_data_lake_de-stack-overflow/BigQuery/posts_questions*/*.parquet: matched no files.
[2022-04-07 19:18:03,797] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=load_to_BigQuery, task_id=create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table, execution_date=20110301T000000, start_date=20220407T191801, end_date=20220407T191803
[2022-04-07 19:18:03,905] {standard_task_runner.py:98} ERROR - Failed to execute job 12459 for task create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/de-stack-overflow/datasets/stack_overflow_data/tables?prettyPrint=false: Error while reading table: posts_questions_stack_overflow_data_external_table, error message: Failed to expand table posts_questions_stack_overflow_data_external_table with file pattern gs://dtc_data_lake_de-stack-overflow/BigQuery/posts_questions*/*.parquet: matched no files.; 917)
[2022-04-07 19:18:03,976] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-07 19:18:04,109] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:10:12,335] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table scheduled__2011-03-01T00:00:00+00:00 [queued]>
[2022-04-07 22:10:12,402] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table scheduled__2011-03-01T00:00:00+00:00 [queued]>
[2022-04-07 22:10:12,409] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:10:12,410] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:10:12,410] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:10:12,678] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table> on 2011-03-01 00:00:00+00:00
[2022-04-07 22:10:12,695] {standard_task_runner.py:52} INFO - Started process 2266 to run task
[2022-04-07 22:10:12,708] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table', 'scheduled__2011-03-01T00:00:00+00:00', '--job-id', '13565', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmp78rtzzoo', '--error-file', '/tmp/tmpv9oj10es']
[2022-04-07 22:10:12,710] {standard_task_runner.py:80} INFO - Job 13565: Subtask create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table
[2022-04-07 22:10:12,851] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table scheduled__2011-03-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:10:13,036] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:10:13,098] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2011-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2011-03-01T00:00:00+00:00
[2022-04-07 22:10:13,100] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:10:13,582] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_posts_questions.create_posts_questions_stack_overflow_data_external_table, execution_date=20110301T000000, start_date=20220407T221012, end_date=20220407T221013
[2022-04-07 22:10:13,639] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:10:13,730] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
