[2022-04-07 19:22:30,681] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2015-09-01T00:00:00+00:00 [queued]>
[2022-04-07 19:22:30,701] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2015-09-01T00:00:00+00:00 [queued]>
[2022-04-07 19:22:30,701] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:22:30,701] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:22:30,701] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:22:30,941] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_users.create_users_stack_overflow_data_external_table> on 2015-09-01 00:00:00+00:00
[2022-04-07 19:22:30,956] {standard_task_runner.py:52} INFO - Started process 2857 to run task
[2022-04-07 19:22:30,978] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_users.create_users_stack_overflow_data_external_table', 'scheduled__2015-09-01T00:00:00+00:00', '--job-id', '12741', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmptqjpfc35', '--error-file', '/tmp/tmprm4d00wa']
[2022-04-07 19:22:30,984] {standard_task_runner.py:80} INFO - Job 12741: Subtask create_external_users.create_users_stack_overflow_data_external_table
[2022-04-07 19:22:31,149] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2015-09-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:22:31,274] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:22:31,350] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_users.create_users_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2015-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2015-09-01T00:00:00+00:00
[2022-04-07 19:22:31,353] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:22:31,835] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_users.create_users_stack_overflow_data_external_table, execution_date=20150901T000000, start_date=20220407T192230, end_date=20220407T192231
[2022-04-07 19:22:31,880] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 19:22:31,946] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:15:59,793] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2015-09-01T00:00:00+00:00 [queued]>
[2022-04-07 22:15:59,864] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2015-09-01T00:00:00+00:00 [queued]>
[2022-04-07 22:15:59,864] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:15:59,864] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:15:59,864] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:16:00,674] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_users.create_users_stack_overflow_data_external_table> on 2015-09-01 00:00:00+00:00
[2022-04-07 22:16:00,741] {standard_task_runner.py:52} INFO - Started process 5199 to run task
[2022-04-07 22:16:00,789] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_users.create_users_stack_overflow_data_external_table', 'scheduled__2015-09-01T00:00:00+00:00', '--job-id', '13996', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpsnnn00_y', '--error-file', '/tmp/tmp1forgbxf']
[2022-04-07 22:16:00,790] {standard_task_runner.py:80} INFO - Job 13996: Subtask create_external_users.create_users_stack_overflow_data_external_table
[2022-04-07 22:16:01,178] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2015-09-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:16:01,480] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:16:01,584] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_users.create_users_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2015-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2015-09-01T00:00:00+00:00
[2022-04-07 22:16:01,587] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:16:04,893] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_users.create_users_stack_overflow_data_external_table, execution_date=20150901T000000, start_date=20220407T221559, end_date=20220407T221604
[2022-04-07 22:16:04,951] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:16:05,020] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
