[2022-04-07 19:24:07,913] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2016-12-01T00:00:00+00:00 [queued]>
[2022-04-07 19:24:08,044] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2016-12-01T00:00:00+00:00 [queued]>
[2022-04-07 19:24:08,056] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:24:08,060] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:24:08,061] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:24:09,168] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_users.create_users_stack_overflow_data_external_table> on 2016-12-01 00:00:00+00:00
[2022-04-07 19:24:09,338] {standard_task_runner.py:52} INFO - Started process 3631 to run task
[2022-04-07 19:24:09,495] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_users.create_users_stack_overflow_data_external_table', 'scheduled__2016-12-01T00:00:00+00:00', '--job-id', '12855', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpsvd756m0', '--error-file', '/tmp/tmprbczvsli']
[2022-04-07 19:24:09,496] {standard_task_runner.py:80} INFO - Job 12855: Subtask create_external_users.create_users_stack_overflow_data_external_table
[2022-04-07 19:24:10,077] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2016-12-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:24:10,761] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:24:10,859] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_users.create_users_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2016-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2016-12-01T00:00:00+00:00
[2022-04-07 19:24:10,861] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:24:12,102] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_users.create_users_stack_overflow_data_external_table, execution_date=20161201T000000, start_date=20220407T192407, end_date=20220407T192412
[2022-04-07 19:24:12,249] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 19:24:12,478] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:17:32,257] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2016-12-01T00:00:00+00:00 [queued]>
[2022-04-07 22:17:32,332] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2016-12-01T00:00:00+00:00 [queued]>
[2022-04-07 22:17:32,333] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:17:32,333] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:17:32,333] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:17:32,798] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_users.create_users_stack_overflow_data_external_table> on 2016-12-01 00:00:00+00:00
[2022-04-07 22:17:32,872] {standard_task_runner.py:52} INFO - Started process 5959 to run task
[2022-04-07 22:17:32,914] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_users.create_users_stack_overflow_data_external_table', 'scheduled__2016-12-01T00:00:00+00:00', '--job-id', '14112', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpjt7hxg8b', '--error-file', '/tmp/tmpt099ktht']
[2022-04-07 22:17:32,915] {standard_task_runner.py:80} INFO - Job 14112: Subtask create_external_users.create_users_stack_overflow_data_external_table
[2022-04-07 22:17:33,371] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2016-12-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:17:33,737] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:17:33,833] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_users.create_users_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2016-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2016-12-01T00:00:00+00:00
[2022-04-07 22:17:33,836] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:17:34,518] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_users.create_users_stack_overflow_data_external_table, execution_date=20161201T000000, start_date=20220407T221732, end_date=20220407T221734
[2022-04-07 22:17:34,664] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:17:34,859] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
