[2022-04-07 19:25:03,893] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2017-09-01T00:00:00+00:00 [queued]>
[2022-04-07 19:25:04,002] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2017-09-01T00:00:00+00:00 [queued]>
[2022-04-07 19:25:04,003] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:25:04,003] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:25:04,003] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:25:04,756] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_users.create_users_stack_overflow_data_external_table> on 2017-09-01 00:00:00+00:00
[2022-04-07 19:25:04,805] {standard_task_runner.py:52} INFO - Started process 4034 to run task
[2022-04-07 19:25:04,884] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_users.create_users_stack_overflow_data_external_table', 'scheduled__2017-09-01T00:00:00+00:00', '--job-id', '12920', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpexixl__t', '--error-file', '/tmp/tmp6eur9o0i']
[2022-04-07 19:25:04,892] {standard_task_runner.py:80} INFO - Job 12920: Subtask create_external_users.create_users_stack_overflow_data_external_table
[2022-04-07 19:25:05,289] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2017-09-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:25:05,541] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:25:05,725] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_users.create_users_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2017-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-09-01T00:00:00+00:00
[2022-04-07 19:25:05,733] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:25:08,739] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_users.create_users_stack_overflow_data_external_table, execution_date=20170901T000000, start_date=20220407T192503, end_date=20220407T192508
[2022-04-07 19:25:08,950] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 19:25:09,149] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:18:22,355] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2017-09-01T00:00:00+00:00 [queued]>
[2022-04-07 22:18:22,399] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2017-09-01T00:00:00+00:00 [queued]>
[2022-04-07 22:18:22,403] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:18:22,403] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:18:22,403] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:18:22,638] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_users.create_users_stack_overflow_data_external_table> on 2017-09-01 00:00:00+00:00
[2022-04-07 22:18:22,649] {standard_task_runner.py:52} INFO - Started process 6382 to run task
[2022-04-07 22:18:22,662] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_users.create_users_stack_overflow_data_external_table', 'scheduled__2017-09-01T00:00:00+00:00', '--job-id', '14186', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmplz00hzg1', '--error-file', '/tmp/tmp2iwxwevg']
[2022-04-07 22:18:22,664] {standard_task_runner.py:80} INFO - Job 14186: Subtask create_external_users.create_users_stack_overflow_data_external_table
[2022-04-07 22:18:22,839] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2017-09-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:18:23,005] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:18:23,065] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_users.create_users_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2017-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-09-01T00:00:00+00:00
[2022-04-07 22:18:23,069] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:18:23,614] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_users.create_users_stack_overflow_data_external_table, execution_date=20170901T000000, start_date=20220407T221822, end_date=20220407T221823
[2022-04-07 22:18:23,728] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:18:23,904] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
