[2022-04-07 22:22:26,956] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2021-02-01T00:00:00+00:00 [queued]>
[2022-04-07 22:22:27,003] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2021-02-01T00:00:00+00:00 [queued]>
[2022-04-07 22:22:27,004] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:22:27,004] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:22:27,004] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:22:27,405] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_users.create_users_stack_overflow_data_external_table> on 2021-02-01 00:00:00+00:00
[2022-04-07 22:22:27,450] {standard_task_runner.py:52} INFO - Started process 8570 to run task
[2022-04-07 22:22:27,481] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_users.create_users_stack_overflow_data_external_table', 'scheduled__2021-02-01T00:00:00+00:00', '--job-id', '14514', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmp27swukx7', '--error-file', '/tmp/tmpl0z0boze']
[2022-04-07 22:22:27,504] {standard_task_runner.py:80} INFO - Job 14514: Subtask create_external_users.create_users_stack_overflow_data_external_table
[2022-04-07 22:22:27,757] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_users.create_users_stack_overflow_data_external_table scheduled__2021-02-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:22:27,935] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:22:27,992] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_users.create_users_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2021-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-01T00:00:00+00:00
[2022-04-07 22:22:27,995] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:22:28,527] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_users.create_users_stack_overflow_data_external_table, execution_date=20210201T000000, start_date=20220407T222226, end_date=20220407T222228
[2022-04-07 22:22:28,566] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:22:28,614] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
